[package]
name = "offline_first_core"
version = "0.0.1"
edition = "2021"

[lib]
name = "offline_first_core"
crate-type = ["cdylib", "staticlib"]

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
strip = true
panic = 'abort'

[dependencies]
redb = "2.4.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.116"