[package]
name = "offline_first_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "offline_first_core"
crate-type = ["cdylib", "staticlib"]

[profile.release]
opt-level = 'z'  # Optimizar para tamaño
lto = true       # Link Time Optimization
codegen-units = 1
strip = true     # Eliminar símbolos de depuración
panic = 'abort'  # Remover código de manejo de pánico

[dependencies]
sled = "0.34.7"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.116"