#!/usr/bin/env bash
# Runs the benchmarks of examples/bench.rs at 10 000, 100 000 and 1 000 000
# rows and writes BENCHMARKS.md with the hardware, the versions and the
# tables. Usage: tool/bench.sh [rows ...]
set -euo pipefail
cd "$(dirname "$0")/.."

SIZES=("$@")
if [ ${#SIZES[@]} -eq 0 ]; then
  SIZES=(10000 100000 1000000)
fi

cargo build --release --example bench >/dev/null

case "$(uname -s)" in
  Darwin)
    CPU="$(sysctl -n machdep.cpu.brand_string)"
    MEMORY="$(( $(sysctl -n hw.memsize) / 1073741824 )) GiB"
    OS="macOS $(sw_vers -productVersion)"
    ;;
  Linux)
    CPU="$(grep -m1 'model name' /proc/cpuinfo | cut -d: -f2 | sed 's/^ //')"
    MEMORY="$(( $(grep MemTotal /proc/meminfo | awk '{print $2}') / 1048576 )) GiB"
    OS="$(. /etc/os-release && echo "$PRETTY_NAME")"
    ;;
  *)
    CPU="unknown"; MEMORY="unknown"; OS="$(uname -s)"
    ;;
esac

{
  echo "# Benchmarks"
  echo
  echo "Generated by \`tool/bench.sh\` on $(date -u +%Y-%m-%d)."
  echo
  echo "- CPU: $CPU"
  echo "- Memory: $MEMORY"
  echo "- OS: $OS"
  echo "- $(rustc --version)"
  echo "- offline_first_core $(grep -m1 '^version' Cargo.toml | cut -d'"' -f2), LMDB 1.0.2"
  echo
  echo "Every write is durable (\`Durability::Full\`: one flush per commit, \`F_FULLFSYNC\`"
  echo "on Apple hardware), the same for every row. Each number is the median of five"
  echo "runs on a fresh database. \"wire\" rows send the same request as JSON through"
  echo "\`ofc_execute\`, as the Dart SDKs do; the Rust API rows decode the rows into"
  echo "\`serde_json::Value\`, while a plain wire \`select\` sends them as stored."
  for rows in "${SIZES[@]}"; do
    echo
    echo "## $rows rows"
    echo
    ./target/release/examples/bench "$rows" | tail -n +3
  done
} > BENCHMARKS.md

echo "BENCHMARKS.md written for: ${SIZES[*]}"
